# -*- coding: utf-8 -*-
"""FIRST CE-CAMBO

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1znczN7S_UOavLV-2fafX4g0gic1Myh1v
"""

pip install -q streamlit folium streamlit-folium openpyxl pydeck

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/app_v6_10.py
# import streamlit as st
# import sqlite3
# import os
# import hashlib
# import html
# import base64
# import pandas as pd
# from datetime import datetime
# import unicodedata
# import shutil
# import re
# from PIL import Image
# import pytesseract
# import io
# import math
# import random
# import requests
# import json
# 
# try:
#     import pydeck as pdk
# except ImportError:
#     pass
# 
# try:
#     import folium
#     from folium.plugins import Draw
#     from streamlit_folium import st_folium
# except ImportError:
#     pass
# 
# # =========================================================
# # CE-CAMBO V12.0 PRO (Integrated Urban Context Scanner)
# # =========================================================
# st.set_page_config(page_title="CE-CAMBO PRO V12.0", page_icon="🏗️", layout="wide", initial_sidebar_state="expanded")
# 
# BASE_DIR = os.path.dirname(os.path.abspath(__file__))
# DATA_DIR = os.path.join(BASE_DIR, "data")
# UPLOADS_DIR = os.path.join(BASE_DIR, "uploads")
# PARTICIPANTS_DIR = os.path.join(UPLOADS_DIR, "participants")
# MASTER_DIR = os.path.join(UPLOADS_DIR, "master")
# COURSES_DIR = os.path.join(UPLOADS_DIR, "courses")
# PROFILES_DIR = os.path.join(UPLOADS_DIR, "profiles")
# GEN_LIB_DIR = os.path.join(UPLOADS_DIR, "general_library")
# DB = os.path.join(DATA_DIR, "ce_cambo_pro.db")
# 
# for folder in [DATA_DIR, UPLOADS_DIR, PARTICIPANTS_DIR, MASTER_DIR, COURSES_DIR, PROFILES_DIR, GEN_LIB_DIR]:
#     os.makedirs(folder, exist_ok=True)
# 
# ADMIN_EMAIL = "admin@ce-cambo.com"
# try:
#     ADMIN_PASSWORD = st.secrets["ADMIN_PASSWORD"]
# except:
#     ADMIN_PASSWORD = os.getenv("ADMIN_PASSWORD", "CECAMBO2026")
# 
# CONTACT_EMAIL = "sangkosal40@gmail.com"
# CONTACT_PHONE = "081 749 148"
# 
# CATEGORIES = ["AutoCAD / CAD", "Revit / BIM", "Structural Engineering", "Survey", "Architecture", "Quantity Survey", "Report / Document", "Learning Material", "Other"]
# ALLOWED_TYPES = ["pdf", "doc", "docx", "dwg", "dxf", "rvt", "rfa", "skp", "xlsx", "xls", "csv", "pptx", "jpg", "jpeg", "png", "txt", "zip", "py", "mp4", "mov"]
# 
# def db_connection(): return sqlite3.connect(DB, check_same_thread=False)
# 
# def init_database():
#     with db_connection() as conn:
#         cur = conn.cursor()
#         cur.execute("""CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, email TEXT UNIQUE NOT NULL, phone TEXT, password TEXT NOT NULL, role TEXT DEFAULT 'participant', status TEXT DEFAULT 'active', profile_pic TEXT, created_at TEXT)""")
#         try: cur.execute("ALTER TABLE users ADD COLUMN profile_pic TEXT")
#         except sqlite3.OperationalError: pass
#         cur.execute("""CREATE TABLE IF NOT EXISTS files (id INTEGER PRIMARY KEY AUTOINCREMENT, filename TEXT NOT NULL, original_name TEXT NOT NULL, category TEXT, owner TEXT, file_type TEXT, file_size REAL, location TEXT, uploaded_at TEXT)""")
#         cur.execute("""CREATE TABLE IF NOT EXISTS course_files (id INTEGER PRIMARY KEY AUTOINCREMENT, course_name TEXT NOT NULL, lesson_name TEXT, filename TEXT NOT NULL, original_name TEXT NOT NULL, uploaded_by TEXT, uploaded_at TEXT)""")
#         cur.execute("""CREATE TABLE IF NOT EXISTS activities (id INTEGER PRIMARY KEY AUTOINCREMENT, user TEXT, action TEXT, created_at TEXT)""")
#         cur.execute("""CREATE TABLE IF NOT EXISTS forum_posts (id INTEGER PRIMARY KEY AUTOINCREMENT, user_name TEXT NOT NULL, content TEXT NOT NULL, created_at TEXT)""")
#         conn.commit()
# 
# init_database()
# 
# def log_activity(user, action):
#     try:
#         with db_connection() as conn:
#             conn.execute("INSERT INTO activities (user, action, created_at) VALUES (?, ?, ?)", (user, action, datetime.now().strftime("%Y-%m-%d %H:%M:%S")))
#             conn.commit()
#     except: pass
# 
# def add_forum_post(username, content):
#     if content.strip():
#         with db_connection() as conn:
#             conn.execute("INSERT INTO forum_posts (user_name, content, created_at) VALUES (?, ?, ?)", (username, content.strip(), datetime.now().strftime("%Y-%m-%d %H:%M:%S")))
#             conn.commit()
# 
# def get_forum_posts():
#     try:
#         with db_connection() as conn: return conn.execute("SELECT id, user_name, content, created_at FROM forum_posts ORDER BY id DESC").fetchall()
#     except: return []
# 
# def hash_password(password): return hashlib.sha256(password.encode("utf-8")).hexdigest()
# 
# def create_user(name, email, phone, password):
#     try:
#         with db_connection() as conn:
#             conn.execute("INSERT INTO users (name, email, phone, password, role, status, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)", (name.strip(), email.strip().lower(), phone.strip(), hash_password(password), "participant", "active", datetime.now().strftime("%Y-%m-%d %H:%M:%S")))
#             conn.commit()
#             return True
#     except sqlite3.IntegrityError: return False
# 
# def authenticate_user(email, password):
#     with db_connection() as conn:
#         result = conn.execute("SELECT id, name, email, role, phone, status, profile_pic FROM users WHERE email = ? AND password = ?", (email.strip().lower(), hash_password(password))).fetchone()
#     return result
# 
# def update_profile_pic(email, filename):
#     with db_connection() as conn:
#         conn.execute("UPDATE users SET profile_pic = ? WHERE email = ?", (filename, email))
#         conn.commit()
# 
# def get_all_users():
#     with db_connection() as conn: return conn.execute("SELECT name, role, email, phone, profile_pic, created_at FROM users ORDER BY id DESC").fetchall()
# 
# def get_user_activities(username):
#     with db_connection() as conn: return conn.execute("SELECT action, created_at FROM activities WHERE user = ? ORDER BY id DESC LIMIT 50", (username,)).fetchall()
# 
# def safe_filename(filename):
#     safe_name = re.sub(r'[^a-zA-Z0-9_.-]', '_', os.path.basename(filename))
#     return f"{datetime.now().strftime('%Y%m%d%H%M%S%f')}_{safe_name}"
# 
# def save_file(uploaded_file, category, owner, location="participants"):
#     if uploaded_file is None: return None
#     original_name = os.path.basename(uploaded_file.name)
#     extension = os.path.splitext(original_name)[1].lower().replace(".", "")
#     filename = safe_filename(original_name)
# 
#     directory = MASTER_DIR if location == "master" else GEN_LIB_DIR if location == "general_library" else PARTICIPANTS_DIR
#     path = os.path.join(directory, filename)
#     with open(path, "wb") as f: f.write(uploaded_file.getbuffer())
#     with db_connection() as conn:
#         conn.execute("INSERT INTO files (filename, original_name, category, owner, file_type, file_size, location, uploaded_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)", (filename, original_name, category, owner, extension.upper(), round(uploaded_file.size / (1024 * 1024), 2), location, datetime.now().strftime("%Y-%m-%d %H:%M")))
#         conn.commit()
# 
# def delete_system_file(file_id, table_name, file_path):
#     if table_name not in ["files", "course_files"]: return False
#     try:
#         if os.path.exists(file_path): os.remove(file_path)
#     except Exception: pass
#     with db_connection() as conn:
#         conn.execute(f"DELETE FROM {table_name} WHERE id = ?", (file_id,))
#         conn.commit()
#     return True
# 
# # --- API SERVICES FOR URBAN CONTEXT SCANNER ---
# def geocode_location(query):
#     url = "https://nominatim.openstreetmap.org/search"
#     params = {'q': query, 'format': 'json', 'limit': 1}
#     headers = {'User-Agent': 'CECamboPro/1.0'}
#     try:
#         response = requests.get(url, params=params, headers=headers)
#         if response.status_code == 200 and len(response.json()) > 0:
#             res = response.json()[0]
#             return float(res['lat']), float(res['lon'])
#     except Exception: pass
#     return None, None
# 
# def get_bbox_from_features(features):
#     if not features: return None
#     min_lon, min_lat = float('inf'), float('inf')
#     max_lon, max_lat = float('-inf'), float('-inf')
#     for feat in features:
#         coords = feat['geometry']['coordinates']
#         g_type = feat['geometry']['type']
#         def process_pt(lon, lat):
#             nonlocal min_lon, min_lat, max_lon, max_lat
#             min_lon, min_lat = min(min_lon, lon), min(min_lat, lat)
#             max_lon, max_lat = max(max_lon, lon), max(max_lat, lat)
#         if g_type == 'Point':
#             process_pt(coords[0], coords[1])
#         elif g_type == 'LineString':
#             for pt in coords: process_pt(pt[0], pt[1])
#         elif g_type == 'Polygon':
#             for ring in coords:
#                 for pt in ring: process_pt(pt[0], pt[1])
#     return min_lat, min_lon, max_lat, max_lon
# 
# def fetch_osm_context(min_lat, min_lon, max_lat, max_lon):
#     overpass_url = "https://overpass.openstreetmap.fr/api/interpreter"
#     query = f"""
#     [out:json];
#     (
#       way["building"]({min_lat},{min_lon},{max_lat},{max_lon});
#       way["highway"]({min_lat},{min_lon},{max_lat},{max_lon});
#     );
#     out body;
#     >;
#     out skel qt;
#     """
#     try:
#         headers = {'User-Agent': 'CECamboPro/1.0 (sangkosal40@gmail.com)'}
#         response = requests.get(overpass_url, params={'data': query}, headers=headers, timeout=30)
# 
#         if response.status_code != 200:
#             st.error(f'⚠️ Server ផែនទីមានបញ្ហា (Code: {response.status_code})។ សូមសាកល្បងម្ដងទៀតនៅពេលក្រោយ។')
#             return [], []
# 
#         data = response.json()
#         nodes = {el['id']: [el['lon'], el['lat']] for el in data['elements'] if el['type'] == 'node'}
#         buildings, roads = [], []
# 
#         for el in data['elements']:
#             if el['type'] == 'way' and 'tags' in el:
#                 coords = [nodes[n] for n in el['nodes'] if n in nodes]
#                 if len(coords) < 2: continue
#                 if 'building' in el['tags']:
#                     if coords[0] != coords[-1]: coords.append(coords[0])
#                     h = 9.0
#                     try:
#                         if 'height' in el['tags']: h = float(str(el['tags']['height']).replace('m','').strip())
#                         elif 'building:levels' in el['tags']: h = float(el['tags']['building:levels']) * 3.5
#                     except: pass
#                     buildings.append({"coordinates": [coords], "height": h, "name": el['tags'].get('name', 'Building'), "color": [43, 164, 235, 180]})
#                 elif 'highway' in el['tags']:
#                     roads.append({"coordinates": coords, "name": el['tags'].get('name', 'Road')})
# 
#         if not buildings and not roads:
#             st.error('⚠️ ស្កេនមិនទទួលបានទិន្នន័យទេ! អាចមកពីតំបន់នេះគ្មានទិន្នន័យ 3D ឬ Server ផែនទីកំពុង Block។')
# 
#         return buildings, roads
#     except Exception as e:
#         st.error(f'⚠️ ស្កេនមិនទទួលបានទិន្នន័យទេ! បញ្ហា: {str(e)}')
#         return [], []
# 
# def generate_masterplan_dxf(features, roads, use_local, b_lat, b_lon, b_n, b_e):
#     dxf_lines = ["0", "SECTION", "2", "ENTITIES"]
#     def to_local(lon, lat):
#         if use_local and b_lat is not None and b_lon is not None:
#             d_lat = lat - b_lat
#             d_lon = lon - b_lon
#             y = b_n + (d_lat * 111320.0)
#             x = b_e + (d_lon * 111320.0 * math.cos(math.radians(b_lat)))
#             return x, y
#         return lon, lat
# 
#     for feat in features:
#         geom = feat.get("geometry", {})
#         gtype = geom.get("type")
#         coords = geom.get("coordinates", [])
#         if gtype == "Polygon":
#             for ring in coords:
#                 dxf_lines.extend(["0", "POLYLINE", "8", "Boundary", "66", "1", "70", "1"])
#                 for pt in ring:
#                     x, y = to_local(pt[0], pt[1])
#                     dxf_lines.extend(["0", "VERTEX", "8", "Boundary", "10", str(x), "20", str(y), "30", "0.0"])
#                 dxf_lines.extend(["0", "SEQEND"])
#         elif gtype == "LineString":
#             dxf_lines.extend(["0", "POLYLINE", "8", "Lines", "66", "1", "70", "0"])
#             for pt in coords:
#                 x, y = to_local(pt[0], pt[1])
#                 dxf_lines.extend(["0", "VERTEX", "8", "Lines", "10", str(x), "20", str(y), "30", "0.0"])
#             dxf_lines.extend(["0", "SEQEND"])
#         elif gtype == "Point":
#             x, y = to_local(coords[0], coords[1])
#             dxf_lines.extend(["0", "POINT", "8", "Points", "10", str(x), "20", str(y), "30", "0.0"])
# 
#     for road in roads:
#         dxf_lines.extend(["0", "POLYLINE", "8", "Roads", "66", "1", "70", "0"])
#         for pt in road["coordinates"]:
#             x, y = to_local(pt[0], pt[1])
#             dxf_lines.extend(["0", "VERTEX", "8", "Roads", "10", str(x), "20", str(y), "30", "0.0"])
#         dxf_lines.extend(["0", "SEQEND"])
# 
#     dxf_lines.extend(["0", "ENDSEC", "0", "EOF"])
#     return "\n".join(dxf_lines)
# 
# # Function សម្រាប់បង្កើត 3D Collada (.dae) File ដោយបញ្ជូលទាំងអគារ និងផ្លូវ
# def generate_3d_dae(buildings, roads, use_local, b_lat, b_lon, b_n, b_e):
#     def to_local(lon, lat):
#         if use_local and b_lat is not None and b_lon is not None:
#             d_lat = lat - b_lat
#             d_lon = lon - b_lon
#             y = b_n + (d_lat * 111320.0)
#             x = b_e + (d_lon * 111320.0 * math.cos(math.radians(b_lat)))
#             return round(x, 3), round(y, 3)
#         return round(lon * 111320.0 * math.cos(math.radians(lat)), 3), round(lat * 111320.0, 3)
# 
#     # ================= 1. ទិន្នន័យអគារ (Buildings 3D) =================
#     b_vertices = []
#     b_faces = []
#     b_vcounts = []
#     v_offset = 0
# 
#     for bldg in buildings:
#         coords = bldg.get("coordinates", [[]])[0]
#         h = bldg.get("height", 9.0)
#         if not coords or len(coords) < 3: continue
#         n_pts = len(coords)
#         for pt in coords:
#             x, y = to_local(pt[0], pt[1])
#             b_vertices.extend([x, y, 0.0])
#         for pt in coords:
#             x, y = to_local(pt[0], pt[1])
#             b_vertices.extend([x, y, h])
#         for i in range(n_pts - 1):
#             b_vcounts.append(4)
#             b_faces.extend([v_offset + i, v_offset + i + 1, v_offset + n_pts + i + 1, v_offset + n_pts + i])
#         b_vcounts.append(n_pts - 1)
#         b_faces.extend([v_offset + i for i in reversed(range(n_pts - 1))])
#         b_vcounts.append(n_pts - 1)
#         b_faces.extend([v_offset + n_pts + i for i in range(n_pts - 1)])
#         v_offset += 2 * n_pts
# 
#     b_verts_str = " ".join(map(str, b_vertices))
#     b_vcounts_str = " ".join(map(str, b_vcounts))
#     b_p_str = " ".join(map(str, b_faces))
# 
#     # ================= 2. ទិន្នន័យផ្លូវ (Roads 2D Lines) =================
#     r_vertices = []
#     r_lines = []
#     r_offset = 0
#     r_lines_count = 0
# 
#     for road in roads:
#         coords = road.get("coordinates", [])
#         if not coords or len(coords) < 2: continue
#         start_idx = r_offset
#         for pt in coords:
#             x, y = to_local(pt[0], pt[1])
#             r_vertices.extend([x, y, 0.0])
#             r_offset += 1
#         for i in range(len(coords) - 1):
#             r_lines.extend([start_idx + i, start_idx + i + 1])
#             r_lines_count += 1
# 
#     r_verts_str = " ".join(map(str, r_vertices))
#     r_lines_str = " ".join(map(str, r_lines))
# 
#     # ================= 3. បង្កើត DAE XML Structure =================
#     dae_xml = f'''<?xml version="1.0" encoding="utf-8"?>
# <COLLADA xmlns="http://www.collada.org/2005/11/COLLADASchema" version="1.4.1">
#   <asset>
#     <contributor><author>CE-CAMBO</author></contributor>
#     <unit name="meter" meter="1"/>
#     <up_axis>Z_UP</up_axis>
#   </asset>
#   <library_geometries>
#     <!-- អគារ -->
#     <geometry id="buildings-mesh" name="buildings">
#       <mesh>
#         <source id="buildings-positions">
#           <float_array id="buildings-positions-array" count="{len(b_vertices)}">{b_verts_str}</float_array>
#           <technique_common>
#             <accessor source="#buildings-positions-array" count="{len(b_vertices)//3}" stride="3">
#               <param name="X" type="float"/>
#               <param name="Y" type="float"/>
#               <param name="Z" type="float"/>
#             </accessor>
#           </technique_common>
#         </source>
#         <vertices id="buildings-vertices">
#           <input semantic="POSITION" source="#buildings-positions"/>
#         </vertices>
#         <polylist count="{len(b_vcounts)}">
#           <input semantic="VERTEX" source="#buildings-vertices" offset="0"/>
#           <vcount>{b_vcounts_str}</vcount>
#           <p>{b_p_str}</p>
#         </polylist>
#       </mesh>
#     </geometry>'''
# 
#     if r_vertices:
#         dae_xml += f'''
#     <!-- ផ្លូវ -->
#     <geometry id="roads-mesh" name="roads">
#       <mesh>
#         <source id="roads-positions">
#           <float_array id="roads-positions-array" count="{len(r_vertices)}">{r_verts_str}</float_array>
#           <technique_common>
#             <accessor source="#roads-positions-array" count="{len(r_vertices)//3}" stride="3">
#               <param name="X" type="float"/>
#               <param name="Y" type="float"/>
#               <param name="Z" type="float"/>
#             </accessor>
#           </technique_common>
#         </source>
#         <vertices id="roads-vertices">
#           <input semantic="POSITION" source="#roads-positions"/>
#         </vertices>
#         <lines count="{r_lines_count}">
#           <input semantic="VERTEX" source="#roads-vertices" offset="0"/>
#           <p>{r_lines_str}</p>
#         </lines>
#       </mesh>
#     </geometry>'''
# 
#     dae_xml += '''
#   </library_geometries>
#   <library_visual_scenes>
#     <visual_scene id="Scene" name="Scene">
#       <node id="Buildings" name="Buildings">
#         <instance_geometry url="#buildings-mesh"/>
#       </node>'''
# 
#     if r_vertices:
#         dae_xml += '''
#       <node id="Roads" name="Roads">
#         <instance_geometry url="#roads-mesh"/>
#       </node>'''
# 
#     dae_xml += '''
#     </visual_scene>
#   </library_visual_scenes>
#   <scene>
#     <instance_visual_scene url="#Scene"/>
#   </scene>
# </COLLADA>'''
#     return dae_xml
# 
# def unicode_to_legacy_text(text):
#     if not text: return ""
#     norm_text = text.replace('\u200b', '').replace('\u200c', '').replace('\u200d', '')
#     norm_text = unicodedata.normalize("NFC", norm_text)
#     global_replacements = {'ខ្ញុំ': '´', 'ឲ្យ': '[', 'ឲ': 'eGa', '«': '{', '»': '}', '០':'0', '១':'1', '២':'2', '៣':'3', '៤':'4', '៥':'5', '៦':'6', '៧':'7', '៨':'8', '៩':'9', '។':'.', '៕':'?', 'ៗ':',', '៖':'³', '៛':'E'}
#     for k, v in global_replacements.items(): norm_text = norm_text.replace(k, v)
#     cons_map = {'ក':'k', 'ខ':'x', 'គ':'K', 'ឃ':'X', 'ង':'g', 'ច':'c', 'ឆ':'q', 'ជ':'C', 'ឈ':'Q', 'ញ':'j', 'ដ':'d', 'ឋ':'z', 'ឌ':'D', 'ឍ':'Z', 'ណ':'N', 'ត':'t', 'ថ':'f', 'ទ':'T', 'ធ':'F', 'ន':'n', 'ប':'b', 'ផ':'p', 'ព':'B', 'ភ':'P', 'ម':'m', 'យ':'y', 'រ':'r', 'ល':'l', 'វ':'v', 'ស':'s', 'ហ':'h', 'ឡ':'L', 'អ':'G', 'ឥ':'\\', 'ឯ':'É', 'ឧ':'U', 'ឪ':']'}
#     sub_map = {'្ក':'á', '្ខ':'â', '្គ':'ã', '្ឃ':'ä', '្ង':'¶', '្ច':'©', '្ឆ':'æ', '្ជ':'¢', '្ឈ':'è', '្ញ':'é', '្ដ':'þ', '្ឋ':'æ', '្ឌ':'ì', '្ឍ':'í', '្ណ':'î', '្ត':'þ', '្ថ':'ß', '្ទ':'Þ', '្ធ':'ñ', '្ន':'ñ', '្ប':',', '្ផ':'-', '្ព':'<', '្ភ':'/', '្ម':'µ', '្យ':'ü', '្រ':'R', '្ល':'ø', '្វ':'V', '្ស':'S', '្ហ':'x', '្អ':'¥'}
#     sign_map = { 'ំ':'M', 'ះ':'H', 'ៈ':'"', '់':';', '៉':':', '៊':'/', '៍':'_', '័':'½', '៌':'~', '៏':'¾', '៎':'¿', '៑':'' }
#     syllable_regex = r'([ក-អឥ-ឳឯ])(៉|៊)?((?:្[ក-អ])*)(ា|ិ|ី|ឹ|ឺ|ុ|ូ|ួ|ើ|ឿ|ៀ|េ|ែ|ៃ|ោ|ៅ)?(ំ|ះ|ៈ|់|៍|័|៌|៎|៏|៑)?'
#     def reorder_syllable(match):
#         base, shifter, subs, vowel, sign = match.groups()
#         out_ro = ""; out_subs = ""; has_sub = False
#         if subs:
#             for sc in re.findall(r'(្[ក-អ])', subs):
#                 if sc == '្រ': out_ro = "R"
#                 else: out_subs += sub_map.get(sc, sc); has_sub = True
#         out_base = cons_map.get(base, base)
#         if base == 'ញ': out_base = "Ba" if has_sub else "j"
#         out_shifter = sign_map.get(shifter, '') if shifter else ''
#         out_front = ""; out_vowel = ""
#         if vowel == 'េ': out_front = "e"
#         elif vowel == 'ែ': out_front = "E"
#         elif vowel == 'ៃ': out_front = "é"
#         elif vowel == 'ៀ': out_front = "e"; out_vowel = "o"
#         elif vowel == 'ឿ': out_front = "e"; out_vowel = "O"
#         elif vowel == 'ើ': out_front = "e"; out_vowel = "I"
#         elif vowel == 'ោ': out_front = "e"; out_vowel = "a"
#         elif vowel == 'ៅ': out_front = "e"; out_vowel = "A"
#         elif vowel == 'ា': out_vowel = "a"
#         elif vowel == 'ិ': out_vowel = "i"
#         elif vowel == 'ី': out_vowel = "I"
#         elif vowel == 'ឹ': out_vowel = "w"
#         elif vowel == 'ឺ': out_vowel = "W"
#         elif vowel == 'ុ': out_vowel = "ú" if (has_sub or out_ro) else "u"
#         elif vowel == 'ូ': out_vowel = "Ú" if (has_sub or out_ro) else "U"
#         elif vowel == 'ួ': out_vowel = "Ü" if (has_sub or out_ro) else "Y"
#         if base == 'ប' and vowel in ['ា', 'ោ', 'ៅ']: out_base = ')'
#         out_sign = sign_map.get(sign, sign) if sign else ""
#         return f"{out_front}{out_ro}{out_base}{out_shifter}{out_subs}{out_vowel}{out_sign}"
#     return re.sub(syllable_regex, reorder_syllable, norm_text)
# 
# if "theme" not in st.session_state: st.session_state.theme = "ងងឹត (Dark)"
# if "user" not in st.session_state: st.session_state.user = None
# if "selected_course" not in st.session_state: st.session_state.selected_course = None
# if "selected_file_section" not in st.session_state: st.session_state.selected_file_section = None
# if "limon_input_text" not in st.session_state: st.session_state.limon_input_text = ""
# 
# if "map_center" not in st.session_state: st.session_state.map_center = (11.5761, 104.9230)
# if "map_buildings" not in st.session_state: st.session_state.map_buildings = []
# if "map_roads" not in st.session_state: st.session_state.map_roads = []
# if "map_query" not in st.session_state: st.session_state.map_query = "Wat Phnom, Phnom Penh"
# if "map_key" not in st.session_state: st.session_state.map_key = "map_base_1234"
# if "current_drawings" not in st.session_state: st.session_state.current_drawings = []
# 
# is_dark = st.session_state.theme == "ងងឹត (Dark)"
# theme_colors = {"bg": "#0B0F19" if is_dark else "#F8FAFC", "card_bg": "rgba(22, 28, 45, 0.7)" if is_dark else "rgba(255, 255, 255, 1)", "text": "#E2E8F0" if is_dark else "#0F172A", "sub_text": "#94A3B8" if is_dark else "#475569", "accent1": "#00C9FF" if is_dark else "#0061FF", "accent2": "#92FE9D" if is_dark else "#60EFFF", "border": "rgba(255,255,255,0.1)" if is_dark else "rgba(0,0,0,0.08)"}
# input_bg = "#111827" if is_dark else "#FFFFFF"
# input_text = "#F8FAFC" if is_dark else "#0F172A"
# glow_effect = "glow-dark 3s infinite alternate" if is_dark else "glow-light 3s infinite alternate"
# 
# st.markdown(f"""
# <style>
#     @import url('https://fonts.googleapis.com/css2?family=Kantumruy+Pro:wght@300;400;500;600;700&family=Outfit:wght@300;400;500;600;700&display=swap');
#     @keyframes glow-dark {{ 0% {{ box-shadow: 0 0 10px rgba(128,0,128,0.3), 0 0 15px rgba(0,255,128,0.2); }} 50% {{ box-shadow: 0 0 20px rgba(128,0,128,0.6), 0 0 30px rgba(0,255,128,0.4); }} 100% {{ box-shadow: 0 0 10px rgba(128,0,128,0.3), 0 0 15px rgba(0,255,128,0.2); }} }}
#     @keyframes glow-light {{ 0% {{ box-shadow: 0 0 10px rgba(255, 105, 180, 0.2); }} 50% {{ box-shadow: 0 0 25px rgba(255, 105, 180, 0.6); }} 100% {{ box-shadow: 0 0 10px rgba(255, 105, 180, 0.2); }} }}
#     html, body, [class*="css"] {{ font-family: "Kantumruy Pro", "Outfit", sans-serif; }}
#     .stApp {{ background-color: {theme_colors['bg']} !important; color: {theme_colors['text']} !important; }}
#     .glass-card {{ background: {theme_colors['card_bg']}; backdrop-filter: blur(12px); border: 1px solid {theme_colors['border']}; border-radius: 20px; padding: 24px; margin-bottom: 20px; animation: {glow_effect}; }}
#     .course-icon {{ font-size: 48px; margin-bottom: 15px; background: linear-gradient(135deg, {theme_colors['accent1']}, {theme_colors['accent2']}); -webkit-background-clip: text; -webkit-text-fill-color: transparent; text-align:center; }}
#     .gradient-text {{ background: linear-gradient(90deg, {theme_colors['accent1']} 0%, {theme_colors['accent2']} 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent; font-weight: bold; }}
#     div[data-baseweb="textarea"] > div, div[data-baseweb="input"] > div {{ background-color: {input_bg} !important; }}
#     .stTextArea textarea, .stTextInput input {{ color: {input_text} !important; background-color: {input_bg} !important; -webkit-text-fill-color: {input_text} !important; border: 1px solid {theme_colors['accent1']} !important; font-size: 16px !important; line-height: 1.6; }}
#     .stButton > button {{ color: #FFFFFF !important; background: {theme_colors['accent1']} !important; border: none !important; font-weight: bold !important; font-family: "Kantumruy Pro", sans-serif; }}
#     .stButton > button:hover {{ background: {theme_colors['accent2']} !important; color: #0F172A !important; }}
#     [data-testid="stSidebar"] {{ background-color: {theme_colors['bg']} !important; border-right: 1px solid rgba(255, 105, 180, 0.4) !important; box-shadow: 3px 0 15px rgba(255, 105, 180, 0.5) !important; }}
#     [data-testid="stSidebar"] .stRadio > div > label {{ padding: 8px 15px; border-radius: 10px; transition: all 0.3s ease; cursor: pointer; }}
#     [data-testid="stSidebar"] .stRadio > div > label p {{ color: {theme_colors['text']} !important; font-weight: 500 !important; font-size: 16px !important; opacity: 1 !important; font-family: "Kantumruy Pro", sans-serif; }}
#     [data-testid="stSidebar"] .stRadio > div > label:hover {{ background: linear-gradient(90deg, rgba(255,105,180,0.15) 0%, transparent 100%); transform: translateX(5px); }}
#     [data-testid="stSidebar"] .stRadio > div > label:hover p {{ color: {theme_colors['accent1']} !important; text-shadow: 0 0 5px rgba(0, 201, 255, 0.4); }}
# </style>
# """, unsafe_allow_html=True)
# 
# logo_paths = ["/content/image_bb0f04.jpg", "image_bb0f04.jpg", "/content/logo.jpg", "logo.jpg", "/content/logo.png", "logo.png"]
# logo_found = next((p for p in logo_paths if os.path.exists(p)), None)
# ext = "jpeg"
# logo_b64 = None
# if logo_found:
#     ext = "png" if logo_found.lower().endswith("png") else "jpeg"
#     try:
#         with open(logo_found, "rb") as f: logo_b64 = base64.b64encode(f.read()).decode()
#     except: pass
# 
# if logo_b64:
#     st.sidebar.markdown(f"""<div style="text-align: center; margin-bottom: 20px; margin-top: -50px;"><img src="data:image/{ext};base64,{logo_b64}" style="width: 80%; border-radius: 50%; box-shadow: 0 5px 20px rgba(0, 201, 255, 0.4); border: 2px solid {theme_colors['accent1']};"></div>""", unsafe_allow_html=True)
# else: st.sidebar.markdown("<h2 class='gradient-text' style='text-align:center;'>🏗️ CE-CAMBO V12.0</h2>", unsafe_allow_html=True)
# 
# avatar_header_html = "👤"; avatar_sidebar_html = "<div style='font-size:60px; text-align:center;'>🧑‍💻</div>"
# if st.session_state.user:
#     user = st.session_state.user; pic_file = user.get('profile_pic'); img_path = os.path.join(PROFILES_DIR, pic_file) if pic_file and os.path.exists(os.path.join(PROFILES_DIR, pic_file)) else None
#     if img_path:
#         with open(img_path, "rb") as f: b64_img = base64.b64encode(f.read()).decode()
#         avatar_header_html = f'<img src="data:image/jpeg;base64,{b64_img}" style="width:30px; height:30px; border-radius:50%; object-fit:cover; border:1px solid {theme_colors["accent1"]};">'
#         avatar_sidebar_html = f'<div style="text-align:center;"><img src="data:image/jpeg;base64,{b64_img}" style="width:90px; height:90px; border-radius:50%; object-fit:cover; border:2px solid {theme_colors["accent1"]}; margin-bottom:10px;"></div>'
# 
# theme_choice = st.sidebar.radio("🌓 រចនាប័ទ្ម (Theme):", ["ងងឹត (Dark)", "ភ្លឺ (Light)"], index=0 if is_dark else 1, horizontal=True)
# if theme_choice != st.session_state.theme: st.session_state.theme = theme_choice; st.rerun()
# st.sidebar.divider()
# 
# menu_options = {
#     "ទំព័រដើម (Dashboard)": "🏠", "មេរៀន (Courses)": "📚", "ឯកសារ (Files)": "🗂️",
#     "បំប្លែងអក្សរ (Unicode to Limon)": "🔤", "ទិន្នន័យអង្កេត (Data Survey)": "🌍",
#     "ផែនទី និងគូសវាស (3D/2D Map)": "🗺️", "គណនាសម្ភារៈ និងដែក (Material Calc)": "⚖️",
#     "វេទិកាសួរសំណួរ (Q&A Forum)": "💬", "គណនីរបស់ខ្ញុំ (My Profile)": "👤", "ទំនាក់ទំនង (Contact Us)": "📞"
# } if st.session_state.user else {"ទំព័រដើម (Dashboard)": "🏠", "ចូលគណនី (Login / Register)": "🔑", "ទំនាក់ទំនង (Contact Us)": "📞"}
# 
# selected_menu = st.sidebar.radio("ម៉ឺនុយ (Navigation Menu)", list(menu_options.keys()), format_func=lambda x: f"{menu_options[x]} {x}")
# 
# if st.session_state.user:
#     st.sidebar.divider(); st.sidebar.markdown(avatar_sidebar_html, unsafe_allow_html=True)
#     st.sidebar.markdown(f"<div style='text-align:center; margin-bottom:15px; color:#FFFFFF;'><b>🟢 {user['name']}</b><br><small>{user['role'].upper()}</small></div>", unsafe_allow_html=True)
#     if st.sidebar.button("🚪 ចាកចេញ (Logout)", use_container_width=True):
#         st.session_state.user = None; st.session_state.selected_course = None; st.session_state.selected_file_section = None; st.rerun()
# 
# top_logo_html = f'<img src="data:image/{ext};base64,{logo_b64}" style="height:35px; width:35px; border-radius:50%; margin-right:10px; vertical-align: middle;">' if logo_b64 else '🏗️ '
# st.markdown(f"""<div style="display:flex; justify-content:space-between; align-items:center; padding:15px 25px; background:{theme_colors['card_bg']}; border-radius:20px; border:1px solid {theme_colors['border']}; margin-bottom:30px;"><div style="font-size:24px; font-weight:700;" class="gradient-text">{top_logo_html}CE-CAMBO HUB</div><div style="color:{theme_colors['sub_text']}; font-size:14px; display:flex; align-items:center; gap:10px;"><span>📅 {datetime.now().strftime("%d %b %Y")}</span> | <span style="display:flex; align-items:center; gap:8px;">{avatar_header_html} {html.escape(st.session_state.user["name"] if st.session_state.user else "ភ្ញៀវ (Guest)")}</span></div></div>""", unsafe_allow_html=True)
# 
# if selected_menu == "ទំព័រដើម (Dashboard)":
#     if not st.session_state.user:
#         st.markdown("""<div class="glass-card" style="text-align:center; padding: 40px;"><h1 class="gradient-text" style="font-size: 3em; margin-bottom: 10px;">សូមស្វាគមន៍មកកាន់ CE-CAMBO PRO V12.0</h1><p style="font-size: 1.2em;">វេទិកាឌីជីថលសម្រាប់វិស្វករសំណង់កម្ពុជា</p></div>""", unsafe_allow_html=True)
#         st.markdown("<div class='glass-card' style='text-align:center;'><h3>📽️ ស្វែងយល់ពីកម្មវិធីរបស់យើង</h3><p style='margin-bottom: 20px;'>សូមទស្សនាវីដេអូណែនាំខាងក្រោម ដើម្បីស្វែងយល់ពីរបៀបដែលកម្មវិធីយើងអាចជួយសម្រួលការងារវិស្វកម្មរបស់អ្នក។</p>", unsafe_allow_html=True)
#         video_paths = ["/content/promo.mp4", "promo.mp4", "/content/IMG_3729.MOV", "IMG_3729.MOV"]
#         vid_found = next((vp for vp in video_paths if os.path.exists(vp)), None)
#         if vid_found: st.video(vid_found, autoplay=True, muted=True, loop=True)
#         else: st.info("💡 សូមអូសឯកសារវីដេអូ (**promo.mp4**) ចូលទៅក្នុង Folder `/content` របស់ Colab នោះវានឹងលោតចាក់នៅទីនេះដោយស្វ័យប្រវត្តិ។")
#         st.markdown("</div>", unsafe_allow_html=True)
#     else:
#         st.markdown("""<div style='background: linear-gradient(90deg, rgba(0, 201, 255, 0.1), rgba(96, 239, 255, 0.05)); border-left: 5px solid #00C9FF; padding: 15px 20px; border-radius: 10px; margin-bottom: 25px;'><h4 style='margin-top: 0; color: #00C9FF;'>📢 ព័ត៌មានថ្មីៗពីប្រព័ន្ធ (Announcements)</h4><p style='margin-bottom: 0;'><b>[Admin]:</b> សូមស្វាគមន៍មកកាន់ CE-CAMBO V12.0! បញ្ហាគូសវាស និងផែនទីខ្មៅ ត្រូវបានជួសជុល១០០% ដោយប្រើ Google Satellite!</p></div>""", unsafe_allow_html=True)
#         st.markdown(f"""<div class="glass-card" style="text-align:center; padding: 40px;"><h1 class="gradient-text" style="font-size: 3em; margin-bottom: 10px;">រីករាយការត្រលប់មកវិញ, {st.session_state.user["name"]}!</h1><p style="font-size: 1.2em;">CE-CAMBO PRO V12.0 - ពង្រឹងប្រសិទ្ធភាពការងារវិស្វកម្មរបស់អ្នក</p></div>""", unsafe_allow_html=True)
#         st.markdown("<div class='glass-card' style='text-align:center;'><h3>🎉 វីដេអូស្វាគមន៍ (Welcome Video)</h3><p style='margin-bottom: 20px;'>សូមស្វាគមន៍ការត្រលប់មកកាន់ CE-CAMBO HUB!</p>", unsafe_allow_html=True)
#         welcome_video_paths = ["/content/welcome.mp4", "welcome.mp4"]
#         welcome_vid_found = next((vp for vp in welcome_video_paths if os.path.exists(vp)), None)
#         if welcome_vid_found: st.video(welcome_vid_found, autoplay=True, muted=True, loop=True)
#         else: st.info("💡 សូមអូសឯកសារវីដេអូ (**welcome.mp4**) ចូលទៅក្នុង Folder `/content` របស់ Colab ដើម្បីបង្ហាញវីដេអូស្វាគមន៍នៅទីនេះ។")
#         st.markdown("</div>", unsafe_allow_html=True)
# 
#         with db_connection() as conn:
#             u_cnt = conn.execute("SELECT COUNT(*) FROM users").fetchone()[0]
#             f_cnt = conn.execute("SELECT COUNT(*) FROM files").fetchone()[0]
#             c_cnt = conn.execute("SELECT COUNT(*) FROM course_files").fetchone()[0]
#         col1, col2, col3 = st.columns(3)
#         col1.markdown(f"<div class='glass-card'><h3>👥 អ្នកប្រើប្រាស់សរុប</h3><h1 class='gradient-text'>{u_cnt}</h1></div>", unsafe_allow_html=True)
#         col2.markdown(f"<div class='glass-card'><h3>📁 ឯកសារសរុប</h3><h1 class='gradient-text'>{f_cnt}</h1></div>", unsafe_allow_html=True)
#         col3.markdown(f"<div class='glass-card'><h3>📚 មេរៀនសរុប</h3><h1 class='gradient-text'>{c_cnt}</h1></div>", unsafe_allow_html=True)
# 
# elif selected_menu == "ផែនទី និងគូសវាស (3D/2D Map)":
#     st.markdown("<div class='glass-card'><h3>🗺️ URBAN CONTEXT SCANNER</h3><p>ប្រព័ន្ធស្កេនទាញយកទិន្នន័យផ្លូវ និងអគារ 3D ជុំវិញតំបន់សិក្សារបស់អ្នក ដើម្បី Export ជា Solid ចូល SketchUp តាមរយៈ File (.dae)។</p></div>", unsafe_allow_html=True)
# 
#     try:
#         import folium
#         from folium.plugins import Draw
#         from streamlit_folium import st_folium
#         import pydeck as pdk
# 
#         c2_1, c2_2 = st.columns([1, 2.5])
# 
#         with c2_1:
#             st.markdown('<div class="map-controls-panel">', unsafe_allow_html=True)
# 
#             st.markdown('<div class="map-section-title">📍 SEARCH LOCATION</div>', unsafe_allow_html=True)
#             loc_cols = st.columns([3, 1])
#             with loc_cols[0]:
#                 location_q = st.text_input("ទីតាំង", value=st.session_state.map_query, label_visibility="collapsed", placeholder="Phnom Penh, Cambodia")
#             with loc_cols[1]:
#                 if st.button("🔍", use_container_width=True):
#                     st.session_state.map_query = location_q
#                     with st.spinner("កំពុងស្វែងរក..."):
#                         lat, lon = geocode_location(location_q)
#                         if lat and lon:
#                             st.session_state.map_center = (lat, lon)
#                             st.rerun()
# 
#             st.markdown('<div class="map-section-title">🗺️ BASE MAP PROVIDER</div>', unsafe_allow_html=True)
#             map_type = st.radio("Provider", ["Satellite", "Street"], horizontal=True, label_visibility="collapsed")
# 
#             st.markdown('<div class="map-section-title">⚙️ MAP VECTOR LAYERS</div>', unsafe_allow_html=True)
#             show_boundary = st.toggle("Site Boundary (2D Edit Mode)", value=True)
#             show_3d = st.toggle("3D Context Models", value=True)
# 
#             st.markdown('<div class="map-section-title">🌐 SPATIAL REFERENCE & DATUM</div>', unsafe_allow_html=True)
#             use_local_grid = st.toggle("Local Grid Survey A(N, E)", value=True)
#             if use_local_grid:
#                 col_n, col_e = st.columns(2)
#                 with col_n:
#                     base_n = st.number_input("Northing A(N)", value=1000.0)
#                 with col_e:
#                     base_e = st.number_input("Easting A(E)", value=1000.0)
# 
#             st.markdown("<hr style='margin: 15px 0; border-color: rgba(255,255,255,0.1);'>", unsafe_allow_html=True)
# 
#             if st.button("🏙️ Scan Site (Buildings & Roads)", type="primary", use_container_width=True):
#                 if "current_drawings" in st.session_state and len(st.session_state.current_drawings) > 0:
#                     with st.spinner("កំពុងស្រូបយកទិន្នន័យអគារ និងផ្លូវ..."):
#                         bbox = get_bbox_from_features(st.session_state.current_drawings)
#                         if bbox:
#                             min_lat, min_lon, max_lat, max_lon = bbox
#                             bldgs, roads = fetch_osm_context(min_lat, min_lon, max_lat, max_lon)
#                             st.session_state.map_buildings = bldgs
#                             st.session_state.map_roads = roads
#                             if bldgs or roads:
#                                 st.success(f"ស្កេនបាន {len(bldgs)} អគារ និង {len(roads)} ខ្សែផ្លូវ!")
#                 else:
#                     st.warning("⚠️ សូមគូសព្រំដែន (Boundary) លើផែនទីជាមុនសិន ដើម្បីកំណត់តំបន់ស្កេន!")
# 
#             if st.button("🗑️ Clear Map Data", use_container_width=True):
#                 st.session_state.map_key = "map_base_" + str(random.randint(1000, 9999))
#                 st.session_state.map_buildings = []
#                 st.session_state.map_roads = []
#                 if "current_drawings" in st.session_state:
#                     st.session_state.current_drawings = []
#                 st.rerun()
# 
#             st.markdown('</div>', unsafe_allow_html=True)
# 
#         with c2_2:
#             t_2d, t_3d = st.tabs(["✏️ 2D DRAW & BOUNDARY", "🏙️ 3D CONTEXT VIEW"])
# 
#             center_lat, center_lon = st.session_state.map_center
#             drawn_data = []
# 
#             with t_2d:
#                 if show_boundary:
#                     m = folium.Map(location=[center_lat, center_lon], zoom_start=17, control_scale=True, doubleClickZoom=False)
#                     if map_type == "Satellite":
#                         folium.TileLayer(tiles='https://mt1.google.com/vt/lyrs=y&x={x}&y={y}&z={z}', attr='Google Hybrid', name='Google Satellite').add_to(m)
# 
#                     Draw(
#                         export=False, position='topleft',
#                         draw_options={'polyline': True, 'polygon': True, 'rectangle': True, 'circle': True, 'marker': True, 'circlemarker': False},
#                         edit_options={'edit': True, 'remove': True}
#                     ).add_to(m)
# 
#                     output = st_folium(m, width="100%", height=650, key=st.session_state.map_key, returned_objects=["all_drawings"], return_on_hover=False)
#                     if output and "all_drawings" in output and output["all_drawings"] is not None:
#                         drawn_data = output["all_drawings"]
#                         st.session_state.current_drawings = drawn_data
#                 else:
#                     st.info("💡 Map Vector Layers > Site Boundary ត្រូវបានបិទ។")
# 
#             with t_3d:
#                 if show_3d:
#                     layers = []
#                     if len(st.session_state.map_buildings) > 0:
#                         df_bldgs = pd.DataFrame(st.session_state.map_buildings)
#                         poly_layer = pdk.Layer(
#                             "PolygonLayer", df_bldgs, get_polygon="coordinates", get_elevation="height",
#                             get_fill_color="color", get_line_color="[255, 255, 255, 50]", extruded=True, wireframe=True, pickable=True
#                         )
#                         layers.append(poly_layer)
# 
#                     if len(st.session_state.map_roads) > 0:
#                         df_roads = pd.DataFrame(st.session_state.map_roads)
#                         path_layer = pdk.Layer(
#                             "PathLayer", df_roads, get_path="coordinates", get_color="[255, 204, 0, 200]",
#                             width_scale=1, width_min_pixels=2, pickable=False
#                         )
#                         layers.append(path_layer)
# 
#                     if layers:
#                         view_state = pdk.ViewState(latitude=center_lat, longitude=center_lon, zoom=15.5, pitch=50, bearing=-20)
#                         r = pdk.Deck(layers=layers, initial_view_state=view_state, tooltip={"html": "<b>{name}</b><br/>Height: {height}m", "style": {"color": "white"}})
#                         st.pydeck_chart(r, use_container_width=True)
#                     else:
#                         st.info("មិនទាន់មានទិន្នន័យ 3D ទេ។ សូមគូសព្រំដែន ហើយចុចប៊ូតុង Scan Site។")
#                 else:
#                     st.info("💡 Map Vector Layers > 3D Context Models ត្រូវបានបិទ។")
# 
#         if (len(drawn_data) > 0 or len(st.session_state.map_buildings) > 0 or len(st.session_state.map_roads) > 0) and show_boundary:
#             st.markdown("<hr style='margin: 30px 0; border-color: rgba(255,255,255,0.1);'>", unsafe_allow_html=True)
#             st.markdown("#### 📥 EXPORT MASTER PLAN & 3D MODEL", unsafe_allow_html=True)
# 
#             excel_rows = []
#             pt_idx = 1
#             base_lat, base_lon = None, None
# 
#             if len(drawn_data) > 0:
#                 if use_local_grid:
#                     first_feat = drawn_data[0]
#                     coords = first_feat['geometry']['coordinates']
#                     g_type = first_feat['geometry']['type']
#                     if g_type == "Point": base_lon, base_lat = coords[0], coords[1]
#                     elif g_type == "LineString": base_lon, base_lat = coords[0][0], coords[0][1]
#                     elif g_type == "Polygon": base_lon, base_lat = coords[0][0][0], coords[0][0][1]
# 
#                 for feat in drawn_data:
#                     g_type = feat['geometry']['type']
#                     coords = feat['geometry']['coordinates']
# 
#                     def process_point(lon, lat, pt_name):
#                         if use_local_grid and base_lat is not None and base_lon is not None:
#                             d_lat = lat - base_lat
#                             d_lon = lon - base_lon
#                             d_n = d_lat * 111320.0
#                             d_e = d_lon * 111320.0 * math.cos(math.radians(base_lat))
#                             return {"ល.រ (No.)": pt_idx, "ឈ្មោះចំណុច (Point)": pt_name, "Northing (N)": round(base_n + d_n, 3), "Easting (E)": round(base_e + d_e, 3)}
#                         return {"ល.រ (No.)": pt_idx, "ឈ្មោះចំណុច (Point)": pt_name, "Latitude (N)": round(lat, 6), "Longitude (E)": round(lon, 6)}
# 
#                     if g_type == "Point":
#                         pt_name = f"Center-{pt_idx}" if "radius" in feat.get('properties', {}) else f"P-{pt_idx}"
#                         excel_rows.append(process_point(coords[0], coords[1], pt_name))
#                         pt_idx += 1
#                     elif g_type == "LineString":
#                         for i, pt in enumerate(coords):
#                             excel_rows.append(process_point(pt[0], pt[1], f"L{pt_idx}-P{i+1}"))
#                             pt_idx += 1
#                     elif g_type == "Polygon":
#                         for i, pt in enumerate(coords[0]):
#                             excel_rows.append(process_point(pt[0], pt[1], f"Poly{pt_idx}-P{i+1}"))
#                             pt_idx += 1
# 
#             df_draw = pd.DataFrame(excel_rows)
#             st.dataframe(df_draw, use_container_width=True, height=150)
# 
#             dl_c1, dl_c2, dl_c3 = st.columns([1, 1.5, 1.5])
# 
#             if len(excel_rows) > 0:
#                 output_xl = io.BytesIO()
#                 with pd.ExcelWriter(output_xl, engine='openpyxl') as writer:
#                     df_draw.to_excel(writer, index=False, sheet_name='Survey_Data')
#                 with dl_c1:
#                     st.download_button("📥 Export CSV (N, E)", data=output_xl.getvalue(), file_name="Survey_Coordinates.xlsx", mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", use_container_width=True)
# 
#             dxf_2d = generate_masterplan_dxf(drawn_data, st.session_state.map_roads, use_local_grid, base_lat, base_lon, base_n if use_local_grid else 0, base_e if use_local_grid else 0)
#             with dl_c2:
#                 st.download_button("📥 Export AutoCAD 2D (.dxf)", data=dxf_2d.encode('utf-8'), file_name="2D_MasterPlan.dxf", mime="text/plain", use_container_width=True)
#                 st.caption("ប្លង់ 2D សម្រាប់ AutoCAD")
# 
#             dae_3d = generate_3d_dae(st.session_state.map_buildings, st.session_state.map_roads, use_local_grid, base_lat, base_lon, base_n if use_local_grid else 0, base_e if use_local_grid else 0)
#             with dl_c3:
#                 st.download_button("📥 Export for SketchUp (.dae)", data=dae_3d.encode('utf-8'), file_name="3D_Solid_Model.dae", mime="text/xml", use_container_width=True)
#                 st.caption("អគារ 3D Solid! (Import ចូល SketchUp -> ជ្រើសរើស DAE Files *.dae)")
# 
#     except ImportError:
#         st.error("⚠️ សូមដំឡើង Library ជាមុនសិន។ Run កូដនេះក្នុង Cell ថ្មី៖\n`!pip install folium streamlit-folium openpyxl pydeck`")
# 
# elif selected_menu == "ឯកសារ (Files)":
#     file_sections = [
#         {"id": "general_library", "title": "បណ្ណាល័យទូទៅ (Gen Library)", "icon": "📖", "desc": "សម្រាប់ឯកសារអត្ថបទ (PDF, Word, Excel)"},
#         {"id": "participants", "title": "ឯកសារទូទៅ (File Library)", "icon": "📁", "desc": "សម្រាប់ឯកសារប្លង់ និងវីដេអូ (AutoCAD, Revit, MP4...)"},
#         {"id": "master", "title": "ឯកសារគោល (Master Files)", "icon": "👑", "desc": "ឯកសាររដ្ឋបាល (សម្រាប់តែ Admin)"}
#     ]
#     if not st.session_state.get("selected_file_section"):
#         st.markdown("<div class='glass-card'><h3>🗂️ មជ្ឈមណ្ឌលឯកសារ (Files Center)</h3><p>សូមជ្រើសរើសផ្នែកណាមួយដើម្បីចូលទៅកាន់ឯកសារ ឬវីដេអូ។</p></div>", unsafe_allow_html=True)
#         cols = st.columns(3)
#         for idx, sec in enumerate(file_sections):
#             with cols[idx % 3]:
#                 st.markdown(f"<div class='glass-card' style='text-align:center;'><div class='course-icon'>{sec['icon']}</div><div style='font-size: 20px; font-weight: 700; margin-bottom: 10px; color: {theme_colors['text']};'>{sec['title']}</div><div style='font-size:14px; margin-bottom:15px; color:{theme_colors['sub_text']};'>{sec['desc']}</div></div>", unsafe_allow_html=True)
#                 if st.button(f"ចូលមើល (Enter) {sec['icon']}", key=f"btn_sec_{sec['id']}", use_container_width=True):
#                     st.session_state.selected_file_section = sec['id']; st.rerun()
#     else:
#         selected_sec_id = st.session_state.selected_file_section
#         sec_info = next((s for s in file_sections if s['id'] == selected_sec_id), None)
#         c1, c2 = st.columns([4, 1])
#         c1.markdown(f"<h2>{sec_info['icon']} {sec_info['title']}</h2>", unsafe_allow_html=True)
#         if c2.button("⬅️ ថយក្រោយ (Back)"): st.session_state.selected_file_section = None; st.rerun()
#         dir_map = {"general_library": GEN_LIB_DIR, "participants": PARTICIPANTS_DIR, "master": MASTER_DIR}
#         current_dir = dir_map[selected_sec_id]
#         t_docs, t_vids, t_up = st.tabs(["📄 ឯកសារ (Files)", "🎬 វីដេអូ (Videos)", "📤 បញ្ចូល (Upload)"])
#         with db_connection() as conn: files_db = conn.execute("SELECT id, filename, original_name, category, owner, file_type, file_size, location, uploaded_at FROM files WHERE location = ? ORDER BY id DESC", (selected_sec_id,)).fetchall()
#         docs = [f for f in files_db if f[5].lower() not in ['mp4', 'mov']]; vids = [f for f in files_db if f[5].lower() in ['mp4', 'mov']]
#         with t_docs:
#             search_d = st.text_input("🔎 ស្វែងរកឯកសារ... (Search files)", key="s_docs")
#             for fl in [f for f in docs if search_d.lower() in f[2].lower() or search_d.lower() in f[3].lower()]:
#                 fid, fname, orig_name, cat, owner, f_type, size, loc, udate = fl
#                 st.markdown(f"<div class='glass-card' style='padding:15px; margin-bottom:5px;'><h4 style='margin:0; color:{theme_colors['accent1']}'>📄 {orig_name}</h4><small>{cat} | {size}MB | ដោយ (By): {owner} ថ្ងៃ {udate}</small></div>", unsafe_allow_html=True)
#                 path = os.path.join(current_dir, fname)
#                 if os.path.exists(path):
#                     bc = st.columns([1,1,3])
#                     with bc[0]:
#                         with open(path, "rb") as df: st.download_button("📥 ទាញយក (Download)", df, file_name=orig_name, key=f"dl_d_{fid}")
#                     if st.session_state.user['role'] == 'admin' or st.session_state.user['name'] == owner:
#                         with bc[1]:
#                             if st.button("🗑️ លុប (Delete)", key=f"del_d_{fid}"): delete_system_file(fid, "files", path); st.rerun()
#         with t_vids:
#             search_v = st.text_input("🔎 ស្វែងរកវីដេអូ... (Search videos)", key="s_vids")
#             for fl in [f for f in vids if search_v.lower() in f[2].lower() or search_v.lower() in f[3].lower()]:
#                 fid, fname, orig_name, cat, owner, f_type, size, loc, udate = fl
#                 st.markdown(f"<div class='glass-card' style='padding:15px; margin-bottom:5px;'><h4 style='margin:0; color:{theme_colors['accent2']}'>🎬 {orig_name}</h4><small>{cat} | {size}MB | ដោយ (By): {owner} ថ្ងៃ {udate}</small></div>", unsafe_allow_html=True)
#                 path = os.path.join(current_dir, fname)
#                 if os.path.exists(path):
#                     st.video(path)
#                     bc = st.columns([1,1,3])
#                     with bc[0]:
#                         with open(path, "rb") as df: st.download_button("📥 ទាញយកវីដេអូ (Download)", df, file_name=orig_name, key=f"dl_v_{fid}")
#                     if st.session_state.user['role'] == 'admin' or st.session_state.user['name'] == owner:
#                         with bc[1]:
#                             if st.button("🗑️ លុបវីដេអូ (Delete)", key=f"del_v_{fid}"): delete_system_file(fid, "files", path); st.rerun()
#         with t_up:
#             if selected_sec_id == "master" and st.session_state.user.get("role") != "admin": st.error("🚫 សម្រាប់តែ Admin ប៉ុណ្ណោះ។ (Admin Only)")
#             else:
#                 up_type = st.radio("ជ្រើសរើសប្រភេទបញ្ចូល (Upload Type):", ["ឯកសារ (Document)", "វីដេអូ (Video)"], horizontal=True, key=f"ut_{selected_sec_id}")
#                 u_cat = st.selectbox("ប្រភេទ (Category)", CATEGORIES, key=f"cat_{selected_sec_id}")
#                 if up_type == "ឯកសារ (Document)":
#                     allowed_exts = ["pdf", "doc", "docx", "xls", "xlsx"] if selected_sec_id == "general_library" else [t for t in ALLOWED_TYPES if t not in ["mp4", "mov"]]
#                     up_file = st.file_uploader("ជ្រើសរើសឯកសារ (Select File)", type=allowed_exts, key=f"up_f_{selected_sec_id}")
#                 else:
#                     up_file = st.file_uploader("ជ្រើសរើសវីដេអូ (Select Video)", type=["mp4", "mov"], key=f"up_v_{selected_sec_id}")
#                 if up_file and st.button("បញ្ចូល (Upload)", use_container_width=True, key=f"btn_up_{selected_sec_id}"):
#                     save_file(up_file, u_cat, st.session_state.user["name"], selected_sec_id); st.success("បញ្ចូលបានជោគជ័យ! (Upload Successful)"); st.rerun()
# 
# elif selected_menu == "មេរៀន (Courses)":
#     course_list = [{"title": "AutoCAD Essentials", "desc": "2D drafting.", "icon": "📐"}, {"title": "Revit Structural", "desc": "BIM modeling.", "icon": "🏢"}, {"title": "Structural Design", "desc": "Concrete & steel.", "icon": "🏗️"}, {"title": "Highway Engineering", "desc": "Road design.", "icon": "🛣️"}, {"title": "Project Management", "desc": "Cost estimation.", "icon": "📊"}, {"title": "Quantity Surveying", "desc": "Material takeoffs.", "icon": "📋"}, {"title": "MathCAD Prime", "desc": "Engineering calculations.", "icon": "➗"}]
#     if not st.session_state.selected_course:
#         cols = st.columns(3)
#         for idx, course in enumerate(course_list):
#             with cols[idx % 3]:
#                 st.markdown(f"<div class='glass-card' style='text-align:center;'><div class='course-icon'>{course['icon']}</div><div style='font-size: 20px; font-weight: 700; margin-bottom: 10px; color: {theme_colors['text']};'>{course['title']}</div><div style='font-size:14px; margin-bottom:15px; color:{theme_colors['sub_text']};'>{course['desc']}</div></div>", unsafe_allow_html=True)
#                 if st.button(f"ចូលរៀន (Enter) {course['title']}", key=f"btn_{idx}", use_container_width=True): st.session_state.selected_course = course["title"]; st.rerun()
#     else:
#         selected = st.session_state.selected_course
#         c1, c2 = st.columns([4, 1])
#         c1.markdown(f"<h2>📖 {selected}</h2>", unsafe_allow_html=True)
#         if c2.button("⬅️ ថយក្រោយ (Back)"): st.session_state.selected_course = None; st.rerun()
#         is_admin = st.session_state.user.get("role") == "admin"
#         tabs_list = ["📄 ឯកសារមេរៀន (Materials)", "🎬 វីដេអូមេរៀន (Videos)"]
#         if is_admin: tabs_list.append("📤 បញ្ចូលមេរៀន (Upload)")
#         tabs = st.tabs(tabs_list)
#         with db_connection() as conn: c_files = conn.execute("SELECT id, filename, original_name, uploaded_by, uploaded_at FROM course_files WHERE course_name = ? ORDER BY id DESC", (selected,)).fetchall()
#         docs = [cf for cf in c_files if cf[2].split('.')[-1].lower() not in ['mp4', 'mov']]; vids = [cf for cf in c_files if cf[2].split('.')[-1].lower() in ['mp4', 'mov']]
#         with tabs[0]:
#             if not docs: st.info("មិនទាន់មានឯកសារនៅឡើយទេ។")
#             for cf in docs:
#                 fid, fname, orig_name, up_by, u_date = cf
#                 st.markdown(f"<div class='glass-card' style='padding:15px; margin-bottom:10px;'><b style='color:{theme_colors['accent1']}'>📄 {orig_name}</b><br><small style='color:{theme_colors['sub_text']};'>ដោយ (By): {up_by} | {u_date}</small></div>", unsafe_allow_html=True)
#                 fpath = os.path.join(COURSES_DIR, fname)
#                 if os.path.exists(fpath):
#                     col_dl, col_del = st.columns([1, 1])
#                     with col_dl:
#                         with open(fpath, "rb") as f: st.download_button("📥 ទាញយក (Download)", f, file_name=orig_name, key=f"dl_cd_{fid}")
#                     if is_admin:
#                         with col_del:
#                             if st.button("🗑️ លុប (Delete)", key=f"del_cd_{fid}"): delete_system_file(fid, "course_files", fpath); st.rerun()
#         with tabs[1]:
#             if not vids: st.info("មិនទាន់មានវីដេអូនៅឡើយទេ។")
#             for cf in vids:
#                 fid, fname, orig_name, up_by, u_date = cf
#                 st.markdown(f"<div class='glass-card' style='padding:15px; margin-bottom:10px;'><b style='color:{theme_colors['accent2']}'>🎬 {orig_name}</b><br><small style='color:{theme_colors['sub_text']};'>ដោយ (By): {up_by} | {u_date}</small></div>", unsafe_allow_html=True)
#                 fpath = os.path.join(COURSES_DIR, fname)
#                 if os.path.exists(fpath):
#                     st.video(fpath); col_dl, col_del = st.columns([1, 1])
#                     with col_dl:
#                         with open(fpath, "rb") as f: st.download_button("📥 ទាញយកវីដេអូ (Download)", f, file_name=orig_name, key=f"dl_cv_{fid}")
#                     if is_admin:
#                         with col_del:
#                             if st.button("🗑️ លុបវីដេអូ (Delete)", key=f"del_cv_{fid}"): delete_system_file(fid, "course_files", fpath); st.rerun()
#         if is_admin:
#             with tabs[2]:
#                 up_type = st.radio("ជ្រើសរើសប្រភេទបញ្ចូល (Upload Type):", ["ឯកសារ (Document)", "វីដេអូ (Video)"], horizontal=True, key=f"ctype_course")
#                 up_cfile = st.file_uploader("ជ្រើសរើសឯកសារ", type=[t for t in ALLOWED_TYPES if t not in ["mp4", "mov"]] if up_type == "ឯកសារ (Document)" else ["mp4", "mov"], key="up_cv")
#                 if up_cfile and st.button("បញ្ចូល (Upload)", use_container_width=True):
#                     fname = safe_filename(up_cfile.name)
#                     with open(os.path.join(COURSES_DIR, fname), "wb") as f: f.write(up_cfile.getbuffer())
#                     with db_connection() as conn:
#                         conn.execute("INSERT INTO course_files (course_name, lesson_name, filename, original_name, uploaded_by, uploaded_at) VALUES (?, ?, ?, ?, ?, ?)", (selected, "General", fname, up_cfile.name, st.session_state.user["name"], datetime.now().strftime("%Y-%m-%d %H:%M")))
#                         conn.commit()
#                     st.success("បញ្ចូលបានជោគជ័យ! (Upload Successful)"); st.rerun()
# 
# elif selected_menu == "វេទិកាសួរសំណួរ (Q&A Forum)":
#     st.markdown("<div class='glass-card'><h3>💬 វេទិកាសួរសំណួរ (Q&A Forum)</h3><p>ចែករំលែកចំណេះដឹង និងសួរសំណួរទៅកាន់សមាជិកវិស្វករផ្សេងទៀត។</p></div>", unsafe_allow_html=True)
#     post_content = st.text_area("សរសេរសំណួរ ឬការចែករំលែករបស់អ្នកនៅទីនេះ... (Write your post here...)", height=100, key="qa_input")
#     if st.button("📝 បង្ហោះ (Post)", use_container_width=True):
#         if post_content.strip():
#             add_forum_post(st.session_state.user["name"], post_content); st.success("បង្ហោះបានជោគជ័យ! (Posted successfully)"); st.rerun()
#         else: st.warning("សូមសរសេរអ្វីមួយមុននឹងបង្ហោះ! (Please write something before posting!)")
#     st.divider()
#     posts = get_forum_posts()
#     if posts:
#         for p_id, p_user, p_content, p_time in posts:
#             is_admin_post = (p_user == "System Admin"); user_icon = "👑" if is_admin_post else "🧑‍💻"; color_accent = theme_colors['accent2'] if is_admin_post else theme_colors['accent1']
#             st.markdown(f"""<div class='glass-card' style='padding: 20px; margin-bottom: 15px;'><div style='display: flex; align-items: center; gap: 15px; margin-bottom: 10px;'><div style='font-size: 30px;'>{user_icon}</div><div><b style='font-size: 16px; color: {color_accent};'>{html.escape(p_user)}</b> <br><small style='color: #94A3B8;'>{p_time}</small></div></div><p style='font-size: 16px; white-space: pre-wrap;'>{html.escape(p_content)}</p><div style='margin-top: 15px; padding-top: 10px; border-top: 1px dashed rgba(255,255,255,0.1);'><small style='color: #94A3B8; cursor: pointer;'>💬 ឆ្លើយតប (Reply) - <span style='font-size:12px'>មុខងារឆ្លើយតបនឹងបើកឆាប់ៗនេះ</span></small></div></div>""", unsafe_allow_html=True)
#     else: st.info("មិនទាន់មានសំណួរនៅឡើយទេ។ សូមសរសេរសំណួររបស់អ្នកនៅខាងលើ! (No posts yet. Be the first to ask!)")
# 
# elif selected_menu == "បំប្លែងអក្សរ (Unicode to Limon)":
#     st.markdown("<div style='text-align:center; margin-bottom:20px;'><h1 class='gradient-text' style='font-size: 40px;'>Khmer ➡️ Limon</h1><p style='font-size: 18px;'>បម្លែងអក្សរខ្មែរទៅជា Limon សម្រាប់ប្រើប្រាស់នៅលើ AutoCAD, CapCut ល-ល</p></div>", unsafe_allow_html=True)
#     def clear_text():
#         st.session_state.limon_input_text = ""
#         st.session_state.temp_limon_in = ""
#     def update_text(): st.session_state.limon_input_text = st.session_state.temp_limon_in
#     c1, c2, c3 = st.columns([1, 6, 1])
#     with c2:
#         u_in_l = st.text_area("សរសេរអក្សរខ្មែរ (Unicode) ទីនេះ (ចុច Ctrl+Enter ដើម្បីបម្លែង)៖", value=st.session_state.limon_input_text, height=150, key="temp_limon_in", on_change=update_text, placeholder="ឧ. ក្តីស្រមៃរបស់សិស្សវិស្វករដ៏ល្អម្នាក់។")
#         st.button("🗑️ សម្អាតអត្ថបទ (Clear)", on_click=clear_text)
#         if st.session_state.limon_input_text:
#             converted = unicode_to_legacy_text(st.session_state.limon_input_text)
#             st.markdown(f"<div style='background-color:#1E293B; border-radius:10px; padding:20px; border:1px solid #334155; margin-bottom:15px; margin-top:20px;'><h4 style='color:#00C9FF; margin-top:0;'>លទ្ធផល (Result)</h4><p style='color:#94A3B8; font-size:15px; line-height:1.6;'>⚠️ <b>បញ្ជាក់៖</b> ដោយសារកុំព្យូទ័រមិនមានភ្ជាប់ Font Limon នៅក្នុងប្រព័ន្ធ Website ទើបលោកអ្នកឃើញវាជាអក្សរអង់គ្លេស។ <br>👉 <b>សូមចុចប៊ូតុង Copy នៅជ្រុងខាងស្តាំនៃប្រអប់ខាងក្រោម រួចយកទៅ Paste ក្នុង AutoCAD ហើយប្ដូរ Font ជា Limon S1 នោះលោកអ្នកនឹងទទួលបានអក្សរខ្មែរយ៉ាងស្អាតឥតខ្ចោះ!</b></p></div>", unsafe_allow_html=True)
#             st.text_area("ចម្លងកូដនៅទីនេះ៖", value=converted, height=150, label_visibility="collapsed")
# 
# elif selected_menu == "គណនាសម្ភារៈ និងដែក (Material Calc)":
#     st.markdown("<div class='glass-card'><h3>⚖️ កម្មវិធីគណនាសម្ភារៈសំណង់ និងសាកល្បង (Material, Steel & Tests)</h3></div>", unsafe_allow_html=True)
#     t_steel, t_concrete, t_setting = st.tabs(["⚖️ ទម្ងន់ដែក (Steel Weight)", "🧱 សមាសភាពបេតុង (Concrete Mix Design)", "⏱️ ពេលវេលាកករឹង (Setting Time)"])
#     with t_steel:
#         col1, col2, col3, col4 = st.columns(4)
#         with col1: diameter = st.number_input("អង្កត់ផ្ចិតដែក (mm)", value=12.0, min_value=1.0, step=1.0)
#         with col2: length = st.number_input("ប្រវែងមួយដើម (m)", min_value=0.1, value=12.0, step=0.1)
#         with col3: quantity = st.number_input("ចំនួន (ដើម/pieces)", min_value=1, value=1, step=1)
#         with col4: price_per_ton = st.number_input("តម្លៃក្នុងមួយតោន ($)", value=650.0, min_value=0.0, step=10.0)
#         weight_per_meter = (diameter ** 2) / 162
#         total_weight_kg = weight_per_meter * length * quantity
#         total_weight_ton = total_weight_kg / 1000
#         total_cost = total_weight_ton * price_per_ton
#         st.markdown(f"<div class='glass-card' style='margin-top: 20px;'><h4 style='color:{theme_colors['accent1']}'>📊 លទ្ធផលនៃការគណនាដែក៖</h4><ul><li style='margin-bottom: 10px;'>ទម្ងន់ដែក ១ ម៉ែត្រ (Weight per meter): <b>{weight_per_meter:.3f} kg/m</b></li><li style='margin-bottom: 10px;'>ទម្ងន់សរុប (Total Weight in kg): <b>{total_weight_kg:.3f} kg</b></li><li style='margin-bottom: 10px;'>ទម្ងន់សរុបគិតជាតោន (Total Weight in Ton): <b>{total_weight_ton:.3f} តោន (Tons)</b></li><li style='margin-bottom: 10px;'>តម្លៃសរុបប៉ាន់ស្មាន (Total Cost): <b style='color:#00C9FF; font-size:22px;'>${total_cost:,.2f}</b></li></ul></div>", unsafe_allow_html=True)
#     with t_concrete:
#         c1, c2, c3 = st.columns(3)
#         with c1: fcm28 = st.number_input("កម្លាំងបេតុង fcm28 (MPa)", value=25.0); sigma_c = st.number_input("កម្លាំងស៊ីម៉ងត៍ σc28 (MPa)", value=45.0)
#         with c2: G_coef = st.number_input("មេគុណគ្រួស G", value=4.9); D = st.number_input("ទំហំគ្រួសអតិបរមា D (mm)", value=16.0)
#         with c3: water_est = st.number_input("ទឹកបឋម W (L/m³)", value=174.0); Vv = st.number_input("មាឌខ្យល់ Vv (L/m³)", value=16.0)
#         c4, c5, c6 = st.columns(3)
#         with c4: use_admix = st.checkbox("ប្រើប្រាស់ល្បាយបន្ថែម (Admixture)", value=True); admix_percent = st.number_input("អនុបាត A/C (%)", value=0.6, step=0.1) if use_admix else 0.0
#         with c5: sand_percent = st.number_input("ភាគរយខ្សាច់ S (%)", value=48.0, max_value=100.0)
#         with c6: gravel_percent = st.number_input("ភាគរយថ្ម G (%)", value=52.0, max_value=100.0)
#         if st.button("🔄 គណនាសមាសភាពបេតុង (1m³)", use_container_width=True):
#             c_factor = round(math.sqrt(fcm28 / (G_coef * sigma_c)), 3)
#             w_prime_c_ratio = round((1.0 / 3.15) * ((1.0 - c_factor) / c_factor), 3)
#             w_prime = round(water_est + (1.0 * Vv), 3)
#             cement_kg = round(w_prime / w_prime_c_ratio, 3)
#             admix_L = round((cement_kg * admix_percent / 100.0), 3) if use_admix else 0.0
#             admix_vol = round(admix_L / 1.8, 3) if use_admix else 0.0
#             v_paste = round((cement_kg / 3.15) + (water_est / 1.0) + admix_vol + Vv, 3)
#             v_aggr = round(1000.0 - v_paste, 3)
#             sand_vol = round(v_aggr * (sand_percent / 100.0), 3)
#             gravel_vol = round(v_aggr * (gravel_percent / 100.0), 3)
#             sand_kg = round(sand_vol * 2.65, 3)
#             gravel_kg = round(gravel_vol * 2.65, 3)
#             admix_row = f"<tr style='border-bottom: 1px solid {theme_colors['border']};'><td style='padding:10px;'>🧪 ល្បាយបន្ថែម (Admixture - A)</td><td style='padding:10px; font-weight:bold; color:#00C9FF;'>{admix_L:.3f} L</td></tr>" if use_admix else ""
#             html_output = f"<div class='glass-card' style='margin-top: 20px;'><table style='width:100%; text-align:left; border-collapse: collapse; color:{theme_colors['text']};'><tr style='border-bottom: 1px solid {theme_colors['border']};'><th style='padding:10px;'>សម្ភារៈ (Materials)</th><th style='padding:10px;'>ទម្ងន់/មាឌ ក្នុង 1m³</th></tr><tr style='border-bottom: 1px solid {theme_colors['border']};'><td style='padding:10px;'>🧱 ស៊ីម៉ងត៍ (Cement - C)</td><td style='padding:10px; font-weight:bold; color:#00C9FF;'>{cement_kg:.3f} kg</td></tr><tr style='border-bottom: 1px solid {theme_colors['border']};'><td style='padding:10px;'>💧 ទឹក (Water - W)</td><td style='padding:10px; font-weight:bold; color:#00C9FF;'>{water_est:.3f} L</td></tr>{admix_row}<tr style='border-bottom: 1px solid {theme_colors['border']};'><td style='padding:10px;'>🏜️ ខ្សាច់ (Sand - S)</td><td style='padding:10px; font-weight:bold; color:#00C9FF;'>{sand_kg:.3f} kg</td></tr><tr style='border-bottom: 1px solid {theme_colors['border']};'><td style='padding:10px;'>🪨 ថ្ម/គ្រួស (Gravel - G)</td><td style='padding:10px; font-weight:bold; color:#00C9FF;'>{gravel_kg:.3f} kg</td></tr></table></div>"
#             st.markdown(html_output, unsafe_allow_html=True)
#     with t_setting:
#         c1, c2 = st.columns(2)
#         with c1: t1 = st.number_input("ពេលវេលា t1 (នាទី)", value=0.0, step=1.0); p1 = st.number_input("ជម្រៅ P1 (mm)", value=40.0, step=1.0)
#         with c2: t2 = st.number_input("ពេលវេលា t2 (នាទី)", value=75.0, step=1.0); p2 = st.number_input("ជម្រៅ P2 (mm)", value=35.0, step=1.0)
#         target_p = st.number_input("ជម្រៅគោលដៅស្តង់ដារ (Target Penetration mm)", value=25.0, step=1.0)
#         if st.button("🔄 គណនាពេលវេលាកករឹង", use_container_width=True):
#             if t1 != t2:
#                 ist = t1 + ((p1 - p2) / (t2 - t1)) * (p1 - target_p)
#                 fst = 90 + 1.2 * ist
#                 st.markdown(f"<div class='glass-card' style='margin-top: 20px;'><h4 style='color:{theme_colors['accent1']}'>📊 លទ្ធផលការគណនា៖</h4><ul><li style='margin-bottom: 10px;'>ពេលវេលាកករឹងដំបូង (IST): <b style='color:#00C9FF; font-size:20px;'>{ist:.2f} នាទី</b></li><li style='margin-bottom: 10px;'>ពេលវេលាកករឹងចុងក្រោយ (FST): <b style='color:#00C9FF; font-size:20px;'>{fst:.2f} នាទី</b></li></ul></div>", unsafe_allow_html=True)
# 
# elif selected_menu == "ទិន្នន័យអង្កេត (Data Survey)":
#     st.markdown("<div class='glass-card'><h3>🌍 ទិន្នន័យអង្កេត: រៀបចំទិន្នន័យសម្រាប់ AutoCAD & Civil 3D</h3></div>", unsafe_allow_html=True)
#     t_upload, t_photo = st.tabs(["📁 អានទិន្នន័យពី Excel File", "📷 ទាញទិន្នន័យពីរូបថត (OCR)"])
#     with t_upload:
#         uploaded_excel = st.file_uploader("📂 សូមជ្រើសរើសឯកសារ Excel (.xlsx ឬ .xls)", type=["xlsx", "xls"])
#         if uploaded_excel is not None:
#             xls = pd.ExcelFile(uploaded_excel)
#             c1, c2 = st.columns(2)
#             with c1: selected_sheet = st.selectbox("ជ្រើសរើសផ្ទាំង (Sheet):", xls.sheet_names)
#             with c2: header_row = st.number_input("កំណត់ជួរទីប៉ុន្មានជា Header (កាត់ជួរ Unnamed ចោល):", min_value=0, max_value=20, value=0)
#             df = pd.read_excel(uploaded_excel, sheet_name=selected_sheet, header=header_row)
#             df = df.dropna(how='all', axis=1).dropna(how='all', axis=0)
#             st.dataframe(df, use_container_width=True, height=250)
#             st.markdown("#### ⚙️ ជ្រើសរើសទិន្នន័យដើម្បី Export ទៅកាន់ AutoCAD (Script)")
#             cols = list(df.columns)
#             cc1, cc2, cc3, cc4 = st.columns(4)
#             with cc1: p_col = st.selectbox("ឈ្មោះចំណុច (Point)", ["--None--"] + cols)
#             with cc2: e_col = st.selectbox("Easting (X)", ["--None--"] + cols)
#             with cc3: n_col = st.selectbox("Northing (Y)", ["--None--"] + cols)
#             with cc4: z_col = st.selectbox("Elevation (Z) [Optional]", ["--None--"] + cols)
#             if e_col != "--None--" and n_col != "--None__":
#                 c3d_df = pd.DataFrame()
#                 if p_col != "--None--": c3d_df['Point'] = df[p_col]
#                 c3d_df['Easting'] = df[e_col].astype(str).str.replace(',', '').str.strip()
#                 c3d_df['Northing'] = df[n_col].astype(str).str.replace(',', '').str.strip()
#                 z_vals = df[z_col].astype(str).str.replace(',', '').str.strip() if z_col != "--None--" else ["0"] * len(df)
#                 c3d_df['Elevation'] = z_vals
#                 c3d_df['AutoCAD Script (E,N,Z)'] = c3d_df['Easting'] + "," + c3d_df['Northing'] + "," + c3d_df['Elevation']
#                 st.success("✅ ទិន្នន័យ AutoCAD បានរៀបចំរួចរាល់!")
#                 st.dataframe(c3d_df, use_container_width=True)
#                 c_dl1, c_dl2 = st.columns(2)
#                 output = io.BytesIO()
#                 with pd.ExcelWriter(output, engine='openpyxl') as writer: c3d_df.to_excel(writer, index=False, sheet_name='AutoCAD_Data')
#                 with c_dl1: st.download_button(label="📥 ទាញយកជា Excel (.xlsx)", data=output.getvalue(), file_name='AutoCAD_Survey_Points.xlsx', mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', use_container_width=True)
#                 script_text = "\n".join(c3d_df['AutoCAD Script (E,N,Z)'].tolist())
#                 with c_dl2: st.download_button(label="📥 ទាញយកជា AutoCAD Script (.txt)", data=script_text, file_name='Points_Script.txt', mime='text/plain', use_container_width=True)
#     with t_photo:
#         st.info("💡 អាប់ឡូតរូបថតតារាង Survey របស់អ្នក ដើម្បីទាញយកជាអក្សរ។")
#         img_file = st.file_uploader("📷 ជ្រើសរើសរូបភាព (.jpg, .png)", type=['png', 'jpg', 'jpeg'])
#         if img_file:
#             image = Image.open(img_file)
#             st.image(image, caption="រូបភាពដើម", use_container_width=True)
#             if "ocr_extracted" not in st.session_state or st.session_state.get("ocr_name") != img_file.name:
#                 if st.button("🔍 ទាញយកទិន្នន័យ (Extract Data)"):
#                     with st.spinner("កំពុងវិភាគអក្សរពីរូបថត..."):
#                         try:
#                             st.session_state.ocr_extracted = pytesseract.image_to_string(image)
#                             st.session_state.ocr_name = img_file.name
#                             st.rerun()
#                         except Exception as e: st.error(f"មានបញ្ហា (Error): {e}")
#             if "ocr_extracted" in st.session_state and st.session_state.ocr_name == img_file.name:
#                 lines = [line.split() for line in st.session_state.ocr_extracted.split('\n') if line.strip()]
#                 if lines:
#                     df_img = pd.DataFrame(lines)
#                     df_img.columns = [str(i) for i in df_img.columns]
#                     st.markdown("**លទ្ធផលតារាង Excel បឋម៖**")
#                     st.dataframe(df_img, use_container_width=True)
#                     st.markdown("#### ⚙️ ជ្រើសរើសទិន្នន័យដើម្បី Export ទៅកាន់ AutoCAD")
#                     cols_ocr = list(df_img.columns)
#                     cc1_ocr, cc2_ocr, cc3_ocr, cc4_ocr = st.columns(4)
#                     with cc1_ocr: p_col_ocr = st.selectbox("Point (P)", ["--None--"] + cols_ocr, key="p_ocr")
#                     with cc2_ocr: e_col_ocr = st.selectbox("Easting (X)", ["--None--"] + cols_ocr, key="e_ocr")
#                     with cc3_ocr: n_col_ocr = st.selectbox("Northing (Y)", ["--None--"] + cols_ocr, key="n_ocr")
#                     with cc4_ocr: z_col_ocr = st.selectbox("Elevation (Z)", ["--None--"] + cols_ocr, key="z_ocr")
#                     if e_col_ocr != "--None--" and n_col_ocr != "--None__":
#                         c3d_df_ocr = pd.DataFrame()
#                         if p_col_ocr != "--None--": c3d_df_ocr['Point'] = df_img[p_col_ocr]
#                         c3d_df_ocr['Easting'] = df_img[e_col_ocr].astype(str).str.replace(',', '').str.strip()
#                         c3d_df_ocr['Northing'] = df_img[n_col_ocr].astype(str).str.replace(',', '').str.strip()
#                         z_vals_ocr = df_img[z_col_ocr].astype(str).str.replace(',', '').str.strip() if z_col_ocr != "--None--" else ["0"] * len(df_img)
#                         c3d_df_ocr['Elevation'] = z_vals_ocr
#                         c3d_df_ocr['AutoCAD Script (E,N,Z)'] = c3d_df_ocr['Easting'] + "," + c3d_df_ocr['Northing'] + "," + c3d_df_ocr['Elevation']
#                         st.success("✅ ទិន្នន័យ AutoCAD បានរៀបចំរួចរាល់!")
#                         st.dataframe(c3d_df_ocr, use_container_width=True)
#                         c_dl1_ocr, c_dl2_ocr = st.columns(2)
#                         output_ocr = io.BytesIO()
#                         with pd.ExcelWriter(output_ocr, engine='openpyxl') as writer: c3d_df_ocr.to_excel(writer, index=False, sheet_name='AutoCAD_Data')
#                         with c_dl1_ocr: st.download_button(label="📥 ទាញយកជា Excel (.xlsx)", data=output_ocr.getvalue(), file_name='OCR_AutoCAD_Survey.xlsx', mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', use_container_width=True)
#                         script_text_ocr = "\n".join(c3d_df_ocr['AutoCAD Script (E,N,Z)'].tolist())
#                         with c_dl2_ocr: st.download_button(label="📥 ទាញយកជា AutoCAD Script (.txt)", data=script_text_ocr, file_name='OCR_Points_Script.txt', mime='text/plain', use_container_width=True)
# 
# elif selected_menu == "គណនីរបស់ខ្ញុំ (My Profile)":
#     user = st.session_state.user
#     c1, c2 = st.columns([1, 2])
#     with c1:
#         admin_badge = ""
#         if user['role'].lower() == 'admin': admin_badge = "<div style='background: linear-gradient(90deg, #FF007F, #FF8C00); padding: 5px 15px; border-radius: 20px; color: white; font-weight: bold; font-size: 13px; display: inline-block; margin-bottom: 20px; box-shadow: 0 4px 15px rgba(255, 0, 127, 0.4); text-transform: uppercase; letter-spacing: 1px;'>🔥 Never Give up</div>"
#         profile_html = f"<div class='glass-card' style='text-align:center; padding: 30px 20px;'>{admin_badge}<div style='display: flex; justify-content: center; margin-bottom: 15px;'>{avatar_sidebar_html.replace('90px', '130px')}</div><h2 class='gradient-text' style='margin:0; font-size: 26px;'>{user['name']}</h2><p style='color: #94A3B8; font-size: 14px; letter-spacing: 1px; margin-top: 5px;'>តួនាទី (ROLE): <b style='color: #00C9FF;'>{user['role'].upper()}</b></p><div style='margin-top: 20px; padding-top: 20px; border-top: 1px dashed rgba(148, 163, 184, 0.3);'><p style='margin: 0; font-size: 15px; color: {theme_colors['text']};'>📧 {user['email']}</p></div></div>"
#         st.markdown(profile_html, unsafe_allow_html=True)
#         with st.expander("⚙️ គ្រប់គ្រងរូបភាពគណនី (Manage Profile Picture)"):
#             new_pic = st.file_uploader("បញ្ចូលរូបភាពថ្មី (Upload New Picture)", type=["jpg", "jpeg", "png"])
#             if new_pic and st.button("💾 រក្សាទុករូបភាព (Save Picture)", use_container_width=True):
#                 pic_name = safe_filename(new_pic.name)
#                 with open(os.path.join(PROFILES_DIR, pic_name), "wb") as f: f.write(new_pic.getbuffer())
#                 update_profile_pic(user['email'], pic_name); st.session_state.user['profile_pic'] = pic_name; st.rerun()
#             if user.get('profile_pic') and st.button("🗑️ លុបរូបភាព (Delete Picture)", use_container_width=True):
#                 try: os.remove(os.path.join(PROFILES_DIR, user['profile_pic']))
#                 except: pass
#                 update_profile_pic(user['email'], None); st.session_state.user['profile_pic'] = None; st.rerun()
#     with c2:
#         act_html = "<div class='glass-card'><h4>📈 សកម្មភាពថ្មីៗរបស់ខ្ញុំ (My Recent Activity)</h4><ul style='list-style-type: none; padding: 0; margin-top: 15px;'>"
#         activities = get_user_activities(user['name'])[:10]
#         if activities:
#             for act, time in activities: act_html += f"<li style='padding: 12px 0; border-bottom: 1px solid rgba(148, 163, 184, 0.1);'><span style='color: #00C9FF; font-size: 13px;'>🕰️ {time}</span> <br> <span style='font-size: 15px;'>{act}</span></li>"
#         else: act_html += "<li style='color: #94A3B8; padding-top: 10px;'>មិនមានសកម្មភាពថ្មីៗទេ។ (No recent activity found.)</li>"
#         act_html += "</ul></div>"
#         st.markdown(act_html, unsafe_allow_html=True)
# 
# elif selected_menu == "សហគមន៍ (Community)":
#     st.markdown("<h3>🌐 សមាជិកសហគមន៍ CE-CAMBO (Community Members)</h3>", unsafe_allow_html=True)
#     users = get_all_users(); cols = st.columns(4)
#     for idx, u in enumerate(users):
#         name, role, email, phone, pic, created = u
#         img_html = "<div style='font-size:60px; text-align:center;'>👤</div>"
#         if pic and os.path.exists(os.path.join(PROFILES_DIR, pic)):
#             with open(os.path.join(PROFILES_DIR, pic), "rb") as f: b64 = base64.b64encode(f.read()).decode()
#             img_html = f'<div style="text-align:center;"><img src="data:image/jpeg;base64,{b64}" style="width:100px; height:100px; border-radius:50%; object-fit:cover; border:2px solid {theme_colors["accent1"]};"></div>'
#         elif role == 'admin' and os.path.exists("/content/image_8a99ba.jpg"):
#             with open("/content/image_8a99ba.jpg", "rb") as f: b64 = base64.b64encode(f.read()).decode()
#             img_html = f'<div style="text-align:center;"><img src="data:image/jpeg;base64,{b64}" style="width:100px; height:100px; border-radius:50%; object-fit:cover; border:2px solid {theme_colors["accent1"]};"></div>'
#         with cols[idx % 4]: st.markdown(f"<div class='glass-card' style='padding:15px; text-align:center;'>{img_html}<h4 style='margin:10px 0 5px 0; color:{theme_colors['text']};'>{html.escape(name)}</h4><small style='color:{theme_colors['accent1']};'>{role.upper()}</small></div>", unsafe_allow_html=True)
# 
# elif selected_menu == "ទំនាក់ទំនង (Contact Us)":
#     st.markdown(f"<div class='glass-card' style='text-align:center;'><h1>ផ្នែកជំនួយ (Support)</h1><h2>📧 {CONTACT_EMAIL}</h2><h2>📱 {CONTACT_PHONE}</h2></div>", unsafe_allow_html=True)
# 
# elif selected_menu == "ចូលគណនី (Login / Register)":
#     c1, c2, c3 = st.columns([1, 2, 1])
#     with c2:
#         t_log, t_reg = st.tabs(["🔐 ចូលគណនី (Sign In)", "📝 បង្កើតគណនី (Register)"])
#         with t_log:
#             email = st.text_input("អ៊ីមែល (Email)"); pwd = st.text_input("លេខសម្ងាត់ (Password)", type="password")
#             if st.button("🚀 ចូលគណនី (SIGN IN)", use_container_width=True):
#                 if email.lower() == ADMIN_EMAIL and pwd == ADMIN_PASSWORD:
#                     st.session_state.user = {"id": 0, "name": "System Admin", "email": ADMIN_EMAIL, "role": "admin", "phone": "", "profile_pic": None}
#                     log_activity("System Admin", "Admin login"); st.rerun()
#                 else:
#                     u = authenticate_user(email, pwd)
#                     if u and u[5] == "active":
#                         st.session_state.user = {"id": u[0], "name": u[1], "email": u[2], "role": u[3], "phone": u[4], "profile_pic": u[6]}
#                         log_activity(u[1], "User login"); st.rerun()
#                     else: st.error("អុីមែល ឬ លេខសម្ងាត់មិនត្រឹមត្រូវ។ (Invalid credentials.)")
#         with t_reg:
#             r_name = st.text_input("ឈ្មោះពេញ (Full Name)"); r_email = st.text_input("អាសយដ្ឋានអ៊ីមែល (Email Address)"); r_phone = st.text_input("លេខទូរស័ព្ទ (Phone Number)"); r_pwd = st.text_input("បង្កើតលេខសម្ងាត់ (Create Password)", type="password")
#             if st.button("📝 ចុះឈ្មោះឥឡូវនេះ (REGISTER NOW)", use_container_width=True):
#                 if len(r_pwd) < 6: st.error("លេខសម្ងាត់ត្រូវមានយ៉ាងហោចណាស់ ៦ ខ្ទង់។ (Password must be at least 6 characters.)")
#                 else:
#                     if create_user(r_name, r_email, r_phone, r_pwd):
#                         u = authenticate_user(r_email, r_pwd)
#                         st.session_state.user = {"id": u[0], "name": u[1], "email": u[2], "role": u[3], "phone": u[4], "profile_pic": u[6]}
#                         log_activity(u[1], "Registered and auto-logged in")
#                         st.success("ចុះឈ្មោះបានជោគជ័យ! កំពុងចូលគណនី... (Registration Successful!)")
#                         st.rerun()
#                     else: st.error("ចុះឈ្មោះបរាជ័យ។ អ៊ីមែលនេះអាចមានរួចហើយ។ (Registration failed. Email might already exist.)")

# Function សម្រាប់បង្កើត 3D Collada (.dae) File ជំនួសអោយ .obj (បានជួសជុលរួច)
def generate_3d_dae(buildings, use_local, b_lat, b_lon, b_n, b_e):
    def to_local(lon, lat):
        if use_local and b_lat is not None and b_lon is not None:
            d_lat = lat - b_lat
            d_lon = lon - b_lon
            y = b_n + (d_lat * 111320.0)
            x = b_e + (d_lon * 111320.0 * math.cos(math.radians(b_lat)))
            return round(x, 3), round(y, 3)
        return round(lon * 111320.0 * math.cos(math.radians(lat)), 3), round(lat * 111320.0, 3)

    vertices = []
    faces = []
    vcounts = []

    v_offset = 0
    for bldg in buildings:
        coords = bldg.get("coordinates", [[]])[0]
        h = bldg.get("height", 9.0)
        if not coords or len(coords) < 3: continue

        n_pts = len(coords)

        # Add bottom vertices
        for pt in coords:
            x, y = to_local(pt[0], pt[1])
            vertices.extend([x, y, 0.0])

        # Add top vertices
        for pt in coords:
            x, y = to_local(pt[0], pt[1])
            vertices.extend([x, y, h])

        # Walls
        for i in range(n_pts - 1):
            vcounts.append(4)
            faces.extend([
                v_offset + i,
                v_offset + i + 1,
                v_offset + n_pts + i + 1,
                v_offset + n_pts + i
            ])

        # Bottom face
        vcounts.append(n_pts - 1)
        faces.extend([v_offset + i for i in reversed(range(n_pts - 1))])

        # Top face
        vcounts.append(n_pts - 1)
        faces.extend([v_offset + n_pts + i for i in range(n_pts - 1)])

        v_offset += 2 * n_pts

    verts_str = " ".join(map(str, vertices))
    vcounts_str = " ".join(map(str, vcounts))
    p_str = " ".join(map(str, faces))

    dae_xml = f'''<?xml version="1.0" encoding="utf-8"?>
<COLLADA xmlns="http://www.collada.org/2005/11/COLLADASchema" version="1.4.1">
  <asset>
    <contributor><author>CE-CAMBO</author></contributor>
    <unit name="meter" meter="1"/>
    <up_axis>Z_UP</up_axis>
  </asset>
  <library_geometries>
    <geometry id="buildings-mesh" name="buildings">
      <mesh>
        <source id="buildings-positions">
          <float_array id="buildings-positions-array" count="{len(vertices)}">{verts_str}</float_array>
          <technique_common>
            <accessor source="#buildings-positions-array" count="{len(vertices)//3}" stride="3">
              <param name="X" type="float"/>
              <param name="Y" type="float"/>
              <param name="Z" type="float"/>
            </accessor>
          </technique_common>
        </source>
        <vertices id="buildings-vertices">
          <input semantic="POSITION" source="#buildings-positions"/>
        </vertices>
        <polylist count="{len(vcounts)}">
          <input semantic="VERTEX" source="#buildings-vertices" offset="0"/>
          <vcount>{vcounts_str}</vcount>
          <p>{p_str}</p>
        </polylist>
      </mesh>
    </geometry>
  </library_geometries>
  <library_visual_scenes>
    <visual_scene id="Scene" name="Scene">
      <node id="Buildings" name="Buildings">
        <instance_geometry url="#buildings-mesh"/>
      </node>
    </visual_scene>
  </library_visual_scenes>
  <scene>
    <instance_visual_scene url="#Scene"/>
  </scene>
</COLLADA>'''
    return dae_xml

# ១. តម្លើងកម្មវិធីអានអក្សរ (Tesseract OCR) ទៅក្នុងប្រព័ន្ធ Colab
!apt-get update -qq
!apt-get install -y tesseract-ocr

# ២. តម្លើង Python Library ទាំងអស់ រួមទាំង pytesseract
!pip install -q streamlit folium streamlit-folium openpyxl pydeck pytesseract

import subprocess
import time
import re

# ៣. បិទកម្មវិធីចាស់ដែលកំពុងរត់ចោល ដើម្បីកុំឱ្យជាន់គ្នា
!pkill -f streamlit
!pkill -f cloudflared

print("⏳ កំពុងដំណើរការកម្មវិធី CE-CAMBO ខាងក្រោយខ្នង...")
get_ipython().system_raw('streamlit run /content/app_v6_10.py &')

# រង់ចាំ 5 វិនាទី
time.sleep(5)

print("🌐 កំពុងទាញយក Link ពី Cloudflare សូមរង់ចាំបន្តិច...")
!wget -q -O cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
!chmod +x cloudflared

process = subprocess.Popen(['./cloudflared', 'tunnel', '--url', 'http://localhost:8501'],
                           stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)

# ៤. ស្វែងរក Link ដែលបង្កើតរួច និងបង្ហាញចេញមកក្រៅ
for line in process.stdout:
    if "trycloudflare.com" in line:
        match = re.search(r'(https://[a-zA-Z0-9-]+\.trycloudflare\.com)', line)
        if match:
            print("\n✅ រួចរាល់! សូមចុចលើ Link ខាងក្រោមនេះ ដើម្បីបើកកម្មវិធី៖")
            print("👉", match.group(1))
            break
